name: Deploy FedaPay Woocommerce Plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build

    - name: WordPress Plugin Deploy
      id: deploy
      uses: richard-muvirimi/deploy-wordpress-plugin@development
      with:
        svn-username: ${{ secrets.SVN_USERNAME }}
        svn-password: ${{ secrets.SVN_PASSWORD }}
        plugin-repository: ${{ vars.SVN_REPOSITORY }}
