name: Deploy FedaPay Woocommerce Plugin

on:
  push:
    tags:
      - '*'
env:
  SVN_REPOSITORY: ${{ vars.SVN_REPOSITORY }}
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy script
      run: sh ./deploy/deploy.sh
